# Generated by Django 5.2.12 on 2026-03-11 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('score_earned', models.PositiveIntegerField(default=0)),
                ('time_spent', models.PositiveIntegerField(help_text='Time taken to complete the task in seconds.', validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game Session',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_completion_count', models.PositiveIntegerField(default=5, help_text='Tasks needed to finish this training mission.')),
                ('completion_bonus', models.PositiveIntegerField(default=50)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
