# Generated by Django 5.2.12 on 2026-03-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='player_app.kidprofile'),
        ),
        migrations.AddField(
            model_name='trainingquest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='active_quests', to='player_app.kidprofile'),
        ),
    ]
