# Generated by Django 5.2.12 on 2026-03-11 16:24

import core_common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Oops! This username is already taken by another Huntrix member.'}, help_text='Required. 3-50 characters. Letters, digits and _ only.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), core_common.models.validate_username_regex])),
                ('password', models.CharField(help_text='Password must be at least 8 characters.', max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(help_text='You must be at least 18 years old to manage Huntrix games.', validators=[django.core.validators.MinValueValidator(18)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship_to_kid', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Older Sibling')], default='parent', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Oops! This username is already taken by another Huntrix member.'}, help_text='Required. 3-50 characters. Letters, digits and _ only.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), core_common.models.validate_username_regex])),
                ('password', models.CharField(help_text='Password must be at least 8 characters.', max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(help_text='You must be at least 18 years old to manage Huntrix games.', validators=[django.core.validators.MinValueValidator(18)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='KPOP Academy')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
