# Generated by Django 5.2.12 on 2026-03-11 18:07

import django.core.validators
import django.db.models.deletion
import player_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the kid's name or KPOP stage name.", max_length=50, validators=[django.core.validators.MinLengthValidator(2), player_app.models.validate_stage_name])),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core_common.parent')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core_common.teacher')),
            ],
            options={
                'verbose_name': 'Kid Profile',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('style', models.CharField(choices=[('vocal', 'Vocalist'), ('dance', 'Main Dancer'), ('rap', 'Lead Rapper'), ('visual', 'Visual/Center')], default='vocal', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a KPOP-styled character image.', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Write a short debut introduction!', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='player_app.kidprofile')),
            ],
        ),
    ]
