# Generated by Django 5.2.12 on 2026-03-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidprofile',
            old_name='creator',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='kidprofile',
            name='age',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
