# Generated by Django 5.2.12 on 2026-03-12 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Trainee, Idol, Legend', max_length=50, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('color_code', models.CharField(default='#FF007A', help_text='KPOP Neon color for UI', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Difficulty Levels',
            },
        ),
        migrations.CreateModel(
            name='CountingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(help_text='Describe the mission to the trainee.')),
                ('base_points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('choice_1', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='counting/')),
                ('correct_answer', models.PositiveIntegerField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tasks', to='huntrix_game_app.difficultylevel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArithmeticTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(help_text='Describe the mission to the trainee.')),
                ('base_points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('choice_1', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_a', models.PositiveIntegerField(help_text='First number (e.g., Albums sold in Seoul)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('number_b', models.PositiveIntegerField(help_text='Second number (e.g., Albums sold in Busan)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('operation', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction')], help_text="Choose '+' to combine or '-' to find the difference.", max_length=1)),
                ('correct_answer', models.IntegerField(blank=True, editable=False, null=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tasks', to='huntrix_game_app.difficultylevel')),
            ],
            options={
                'verbose_name': 'Arithmetic Mission',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MazeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(help_text='Describe the mission to the trainee.')),
                ('base_points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('choice_1', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grid', models.JSONField(help_text='2D array: 0=path, 1=wall')),
                ('start_row', models.PositiveIntegerField(default=0)),
                ('start_col', models.PositiveIntegerField(default=0)),
                ('end_row', models.PositiveIntegerField()),
                ('end_col', models.PositiveIntegerField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tasks', to='huntrix_game_app.difficultylevel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(help_text='Describe the mission to the trainee.')),
                ('base_points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('choice_1', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_data', models.JSONField(help_text="Example: ['Mic', 'Stage', '?', 'Award']")),
                ('correct_value', models.CharField(max_length=50)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tasks', to='huntrix_game_app.difficultylevel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
